"""Add metrics to Job model

Revision ID: 902d11500584
Revises: b468aee317a5
Create Date: 2026-03-17 21:13:09.003468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902d11500584'
down_revision: Union[str, Sequence[str], None] = 'b468aee317a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('imported_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('jobs', sa.Column('duplicate_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('jobs', sa.Column('skipped_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'skipped_count')
    op.drop_column('jobs', 'duplicate_count')
    op.drop_column('jobs', 'imported_count')
    # ### end Alembic commands ###
