"""add_confidence_and_traceability_fields

Revision ID: a1be718514ec
Revises: 902d11500584
Create Date: 2026-03-18 17:56:49.811538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1be718514ec'
down_revision: Union[str, Sequence[str], None] = '902d11500584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_summary', sa.Text(), nullable=True))
    op.add_column('financial_movements', sa.Column('confidence_level', sa.String(length=20), nullable=True))
    op.add_column('financial_movements', sa.Column('confidence_flags', sa.Text(), nullable=True))
    op.add_column('financial_movements', sa.Column('source_raw_data', sa.Text(), nullable=True))
    op.add_column('financial_movements', sa.Column('inference_log', sa.Text(), nullable=True))
    op.create_index(op.f('ix_financial_movements_confidence_level'), 'financial_movements', ['confidence_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_movements_confidence_level'), table_name='financial_movements')
    op.drop_column('financial_movements', 'inference_log')
    op.drop_column('financial_movements', 'source_raw_data')
    op.drop_column('financial_movements', 'confidence_flags')
    op.drop_column('financial_movements', 'confidence_level')
    op.drop_column('documents', 'processing_summary')
    # ### end Alembic commands ###
